### ISSUE TITLE
Add Windows as a supported OS

### ISSUE THREAD

**Issue by FatherShawn** [digitalpulp/ballast#15]
- Most tasks in the `scripts/robo/RoboFile.php` have a controller method that checks for the OS and then calls an OS specific function.  Each of those will need a Windows check and Windows function.
- Several of the commands in `.ahoy.yml` hit docker via docker-machine calls.  I would suggest we convert these to additional robo commands that call docker appropriately based on OS.

**Comment by FatherShawn** [comment]
Initial Investigation Tasks:
1. Since Ballast is a PHP based project that depends on Composer, like macOS having PHP and Composer is a prerequisite to even getting started.  Since I'm pretty sure PHP is not installed by default in Windows, we should pull together from other sources some documentation on getting these for Windows.
1. Review [Docker for Windows requirements](https://docs.docker.com/docker-for-windows/install/) 
1. Review [Ahoy for Windows](https://github.com/ahoy-cli/ahoy/issues/48) requirements
1. Consider a package manager for Windows - is [Chocolatey](https://chocolatey.org/) trustworthy, workable?  Is there a better choice or can we install these two plus any requirements just shell?

**Comment by frankcarey** [comment]
Note: I have tested the last release on windows 10 and it worked (you have to have bash installed or you have to change the `entrypoint` to something else (gitbash, etc)

**Comment by enzolutions** [comment]
@frankcarey Which bash did you have, could you explain the changes in **entrypoint**. Thanks in advance

**Comment by FatherShawn** [comment]
closing in favor of #13 with WSL in mind.
