### ISSUE TITLE
Problem with cert file causing nginx to exit

### ISSUE THREAD

**Issue by Skullsneeze** [digitalpulp/ballast#56]
### Description
After following the steps outlined in the README, I try to visit my environment by going to the provided ***.dpulp URL. On this page, I receive a "503 Service Temporarily Unavailable" message.

### Aditional information
When looking at the docker-compose log (using `ahoy log`) I see that the *_web_1 container exits after trying to locate the SSL certificate file.

I see the following error several times:
```
[emerg] 1#1: BIO_new_file("/etc/nginx/certs/***.dpulp.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/certs/***.dpulp.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

### Temporary solution
I managed to get my site running by switching to apache (changed in docker-compose.yml)

**Comment by FatherShawn** [comment]
Thanks for this - looks like we advanced some work that was missing something.  Another workaround is to drop back to `digitalpulp/nginx:stable-alpine-1.0.1` in `setup/docker/docker-compose-template`

**Comment by Skullsneeze** [comment]
Thanks for the quick response. Looks like `digitalpulp/nginx:stable-alpine-1.0.1` is indeed working as well!
