### ISSUE TITLE
Deployment stuck on front-end "completion flag"

### ISSUE THREAD

**Issue by Skullsneeze** [digitalpulp/ballast#57]
### Description
While launching my local environment, or when deploying with Codeship, I reach the following steps:

```
deploy ➜ Waiting for front-end tools to initialize.
deploy ➜ Detected drupal root: /var/www/docroot
deploy ➜ Detected project root: /var/www
deploy ➜ No site_theme_path detected
deploy ➜ Flag complete set to: /var/www/docroot/themes/custom/***/INITIALIZED.txt
```

It seems that there is a 5 minute timeout where the deployment waits for the `INITIALIZED.txt` file to be generated. However, this file never gets generated, and the process exits with the following error:
```
[error]  After a full round of monitoring, node modules never began to compile.
```

The site still works when launched locally though.

### Additional info

While this step is triggered a `BUILDING.txt` file gets generated. This file has no content and remains after the deployment fails.

Is there any way to get around this check, or is there something I'm missing?

**Comment by FatherShawn** [comment]
Yes - we assume that you are using grunt or gulp to compile the theme and an appropriate file can be found in your theme.  If you are in fact using such and the theme name is configured in `setup/config.yml` then that file should be found and executed.  If you are not and you want to skip this check you can either comment out the call to `getDeploymentDependencies` in `\Ballast\Commands\DeployCommands::deployBranch` or you can modify `scripts/robo/src/Commands/FrontEndTrait.php` to always return true.
